CREATE DATABASE SerigrafiaGomez;

USE SerigrafiaGomez;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(255)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE ENUM('admin', 'user') NOT NULL
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_INGRESO DATE NOT NULL,
    SEÑA DECIMAL(10, 2),
    FECHA_FIN DATE,
    IMPORTE_TOTAL DECIMAL(10, 2),
    FACTURADO BOOLEAN,
    TIEMPO_REALIZACION TIME,
    TOMADO_POR INT,
    A_REALIZAR_POR INT,
    INGRESO_POR ENUM('whatsapp', 'telefono', 'email', 'mostrador'),
    METODO_PAGO ENUM('efectivo', 'tarjeta', 'transferencia'),
    ID_CLIENTE INT,
    ESTADO ENUM('no comenzado', 'en proceso', 'realizado', 'entregado'),
	DESCRIPCION TEXT NOT NULL,
    CANTIDAD INT NOT NULL,
    CATEGORIA ENUM('Grabados laser', 'Banderas', 'Impresión en prendas', 'Impresión en objetos', 'Cartelería', 'Ploteos', 'Merchandising', 'Otros'),
    FOREIGN KEY (TOMADO_POR) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (A_REALIZAR_POR) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

INSERT INTO CLIENTE (NOMBRE, TELEFONO, EMAIL)
VALUES ('Juan Perez', '123456789', 'juan.perez@example.com');

INSERT INTO USUARIO (NOMBRE, EMAIL, PASSWORD, ROLE)
VALUES ('Thiago Redondo', 'thiagoredondo@gmail.com', '123456', 'admin');

INSERT INTO PEDIDO (FECHA_INGRESO, SEÑA, FECHA_FIN, IMPORTE_TOTAL, FACTURADO, TIEMPO_REALIZACION, TOMADO_POR, A_REALIZAR_POR, INGRESO_POR, METODO_PAGO, ID_CLIENTE, ESTADO, DESCRIPCION, CANTIDAD, CATEGORIA)
VALUES ('2024-10-20', 50.00, '2024-11-10', 500.00, TRUE, '00:00:00', 1, 1, 'telefono', 'tarjeta', 1, 'no comenzado', 'Impresión de camisetas personalizadas', 10, 'Impresión en prendas');
